name: Build CV PDF

on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
      - '**.sty'
      - '**.cls'
      - 'figures/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile LaTeX (XeLaTeX)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Astuti_CV_MPSA2025.tex   # <-- changed to your actual TeX file
          latexmk_use_xelatex: true

      - name: Publish PDF to docs/
        run: |
          mkdir -p docs
          cp Astuti_CV_MPSA2025.pdf docs/AnNisaTriAstuti_CV.pdf

      - name: Commit updated PDF
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/AnNisaTriAstuti_CV.pdf'
          message: 'Update CV PDF'
          default_author: github_actions
